readme.txt
https://www.cloudflare.com/overview.html returns "The page you are looking for cannot be found."
=> correct overview link

cloudflare.php, readme.txt
Allows Flexible SSL to work transparently.
=> Added SSL header correction functionality into plugin.

src/Test/WordPress/PluginActionsTest.php, src/WordPress/PluginActions.php
Tests were failing:
```
There were 5 errors:
1) CF\WordPress\Test\PluginActionsTest::testReturnApplyDefaultSettingsWithZoneWithPlanBIZ
Undefined offset: 1
/CloudFlare-Wordpress/src/WordPress/PluginActions.php:40
/CloudFlare-Wordpress/src/Test/WordPress/PluginActionsTest.php:83
2) CF\WordPress\Test\PluginActionsTest::testReturnApplyDefaultSettingsWithZoneWithFreePlan
Undefined offset: 1
/CloudFlare-Wordpress/src/WordPress/PluginActions.php:40
/CloudFlare-Wordpress/src/Test/WordPress/PluginActionsTest.php:107
3) CF\WordPress\Test\PluginActionsTest::testReturnApplyDefaultSettingsZoneDetailsThrowsZoneSettingFailException
Undefined offset: 1
/CloudFlare-Wordpress/src/WordPress/PluginActions.php:40
/CloudFlare-Wordpress/src/Test/WordPress/PluginActionsTest.php:120
4) …
```
=> Fixing broken tests.

proxy.php
It looks like this now:
```
$response = null;
if (isCloudFlareCSRFTokenValid($request)) {
$response = $requestRouter->route($request);
} else {
$message = 'CSRF Token not valid.';
$response = array(
'result' => null,
'success' => false,
'errors' => array(
array(
'code' => '',
'message' => $message,
),
),
'messages' => array(),
);
}
/**
* https://codex.wordpress.org/Function_Reference/wp_verify_nonce
*
* Boolean false if the nonce is invalid. Otherwise, returns an integer with the value of:
* 1 – if the nonce has been generated in the past 12 hours or less.
* 2 – if the nonce was generated between 12 and 24 hours ago.
*
* @param CF\API\Request $request
* @return bool
*/
function isCloudFlareCSRFTokenValid($request) {
if($request->getMethod() === 'GET') {
return true;
}
$body = …
```
=> PI-812: Reworking the CSRF logic to be more explicit.

cloudflare.loader.php, cloudflare.php, index.php, src/Hooks/HTTP2ServerPush.php, src/Test/WordPress/HooksTest.php, src/Test/WordPress/ProxyTest.php, src/WordPress/Hooks.php, src/WordPress/PluginActions.php, src/WordPress/Proxy.php, src/WordPress/WordPressClientAPI.php
This is subjective, but IMO makes it easier to spot where the concatenation is happening.
I also fixed  a small type while at it.
Let me know your thoughts :)
=> Use a space around `.`.

README.md, readme.txt, scripts/deployment/publish_github.py
=> Tweak README.md, readme.txt.

src/Test/WordPress/HooksTest.php
=> Fix tests error.

.editorconfig
Match the current style, not the WordPress one.
=> Tweak .editorconfig.

readme.txt
=> Added my username

cloudflare.loader.php
adding PHP_INT_MAX as default cache priority as described here #195
=> Introducing PHP_INT_MAX as default action priority

composer.lock, readme.txt, vendor/cloudflare/cf-ip-rewrite/composer.json, vendor/cloudflare/cf-ip-rewrite/composer.lock, vendor/cloudflare/cf-ip-rewrite/src/CloudFlare/IpRewrite.php, vendor/cloudflare/cf-ip-rewrite/tests/RewriteTest.php, vendor/composer/ClassLoader.php, vendor/composer/LICENSE, vendor/composer/installed.json
Related: https://github.com/cloudflare/Cloudflare-WordPress/issues/201
=> Thellimist/pi 1247 Does not work with Flexible SSL and Nginx when restoring original visitor IPs

.travis.yml
Add php7.1 and php7.2 to `travis.yml`
=> Add php7.1 and php7.2 to travis.yml

.travis.yml, composer.json, composer.lock, src/WordPress/Proxy.php, vendor/cloudflare/cloudflare-plugin-backend/CHANGELOG.md, vendor/cloudflare/cloudflare-plugin-backend/README.md, vendor/cloudflare/cloudflare-plugin-backend/composer.json, vendor/cloudflare/cloudflare-plugin-backend/composer.lock, vendor/cloudflare/cloudflare-plugin-backend/src/API/AbstractAPIClient.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/AbstractPluginActions.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/Client.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/DefaultHttpClient.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/HttpClientInterface.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/Plugin.php, vendor/cloudflare/cloudflare-plugin-backend/src/API/PluginRoutes.php, vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php, vendor/cloudflare/cloudflare-plugin-backend/src/Router/RequestRouter.php, vendor/cloudflare/cloudflare-plugin-backend/src/Test/API/AbstractAPIClientTest.php, vendor/cloudflare/cloudflare-plugin-backend/src/Test/API/AbstractPluginActionsTest.php, vendor/cloudflare/cloudflare-plugin-backend/src/Test/API/ClientTest.php, vendor/cloudflare/cloudflare-plugin-backend/src/Test/API/DefaultHttpClientTest.php, vendor/cloudflare/cloudflare-plugin-backend/src/Test/Router/RequestRouterTest.php, vendor/composer/ClassLoader.php, vendor/composer/autoload_psr4.php, vendor/composer/autoload_static.php, vendor/composer/installed.json
This includes changes required for API Tokens support, and required light changes to `Proxy.php` for
API changes made upstream.
=> Update `cloudflare/cloudflare-plugin-backend` to latest `master`

readme.txt
This reflects the current state of the project.
=> Update readme.txt for contributors, tested version

src/WordPress/Hooks.php
This resolves #251.
```
Notice: Trying to access array offset on value of type null
```
=> Fix PHP 7.4 notice

README.md, cloudflare.loader.php, readme.txt
=> purge URLs on page/post update

src/WordPress/Hooks.php
Purge attachments and their associated resized versions on attachment update.
=> Purge attachment URLs

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
Release v3.7.0
Includes bump cloudflare-plugin-backend v2.3.0 and cloudflare-plugin-frontend v3.1.0
=> Release v3.7.0

config.json, src/WordPress/PluginActions.php
Moves Automatic Cache Management card to speed tab
=> Move Automatic Cache Management card

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
= 3.8.0 - 2020-10-01 =
* Added APO support
* Renamed Automatic Cache Management card to Auto Purge Content On Update
=> Release v3.8.0

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
* Added composer's type=wordpress-plugin for Bedrock users
* Fixed typo in readme.txt
* Fix modify header exception thrown during wp-cron
=> Release v3.8.4

cloudflare.loader.php
Fixes https://github.com/cloudflare/Cloudflare-WordPress/issues/307
=> purge cache on new comment

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
* Added automatic purge cache on new comment
=> Release v3.8.5

cloudflare.php, composer.json, composer.lock, config.json, readme.txt, vendor/composer/installed.json, vendor/symfony/polyfill-ctype/bootstrap.php, vendor/symfony/polyfill-ctype/composer.json
= 3.8.6 - 2020-11-19 =
* Add subdomain support for APO card
=> Release v3.8.6

src/WordPress/Hooks.php
Fixes https://github.com/cloudflare/Cloudflare-WordPress/issues/337
=> add pagination purging

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
= 3.8.8 - 2021-01-13 =
* Add pagination purging
=> Release v3.8.8

src/WordPress/Hooks.php
Reverts cloudflare/Cloudflare-WordPress#339
=> Revert "add pagination purging"

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
= 3.8.9 - 2021-01-14 =
* Revert Add pagination purging
=> Release v3.8.9

readme.txt
=> add jacobbednarz to list of maintainers

cloudflare.php, composer.json, composer.lock, config.json, readme.txt, vendor/composer/installed.json, vendor/dealerdirect/phpcodesniffer-composer-installer/.remarkrc, vendor/dealerdirect/phpcodesniffer-composer-installer/CODE_OF_CONDUCT.md, vendor/dealerdirect/phpcodesniffer-composer-installer/README.md, vendor/dealerdirect/phpcodesniffer-composer-installer/composer.json, vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php
Creates release 3.8.10.
- Add Jacob to the maintainers list
=> release 3.8.10

readme.txt
Updates the `readme.txt` value for `Tested up to:` to show this plugin
works on 5.6
=> readme: Update "tested up to" value

cloudflare.php
For https://github.com/cloudflare/Cloudflare-WordPress/issues/368
=> Bump CLOUDFLARE_MIN_PHP_VERSION to 7.2

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
Updates version to 4.1.0 and release notes
=> release 4.1.0

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
* Allow configuration of Cloudflare credentials via environment variables (#332)
* Prevent purging of cache before comments have been moderated (#356)
* Remove unnecessary symfony/yaml dependency (#374)
=> prepare 4.2.0 release

readme.txt
Adding a FAQ entry for plugin detection with APO and link to the APO support KB.
Unsure if I can verify if more formatting is correct ahead of merging and pushing this.
=> add faq entry to readme.txt for plugin listing

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
* Rewrite PHP 8 bootstrap files for `symfony/polyfill` to be PHP 7 compatible
=> Prepare v4.5.1 for release

.github/workflows/php.yml, .github/workflows/release.yml
Action changed the defaults, let's use the regex explicitly.
=> fix gha-replacer parameters for v2

src/WordPress/Hooks.php
should fix https://github.com/cloudflare/Cloudflare-WordPress/issues/404
depends on: https://github.com/cloudflare/cloudflare-plugin-frontend/pull/181 and https://github.com/cloudflare/cloudflare-plugin-backend/pull/53
=> Purge cache on mobile if APO Cache By Device Type

cloudflare.php, config.json, readme.txt
=> release 4.8.1

src/WordPress/Hooks.php
Takes into account that some of the time, `$urls` will be empty within
the hooks file and if so, we shouldn't try to perform filtering
operations on them.
Closes #462
=> Handle empty `$urls` for Hooks

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
Fix logic for ignoring cache purge operations.
=> release 4.10.1

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
* Updated plugin to be tested on WordPress 6.2
=> release 4.12.0

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
This release deploys the following fix #529.
=> release 4.12.3

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
This release deploys the following fix #508.
=> release 4.12.4

cloudflare.php, composer.json, composer.lock, config.json, readme.txt
**🔖 Summary**
This release includes cloudflare#547 which prevent default settings from enabling Auto Minify due to deprecation.
=> release 4.12.8
