cloudflare.php
src/WordPress/Hooks.php

I'm not sure if you can uninstall a plugin without deactivating it first.  If thats the case can't we just delete this hook since `deactivate()` calls `clearDataStore()` as well?

PI-823: Fixing uninstall hook.

---

cloudflare.loader.php
src/WordPress/Hooks.php
src/WordPress/WordPressClientAPI.php

Allows WP to purge this URLS on post (also page and CPT) update:
- Post URL
- Homepage
- Page for posts (if set)
- Related tags URLs
- Related categories/taxonomies URLs
- HTTP & HTTPS (only if admin from HTTPS)
Doesn't purge on post autosave.
I've tested this on Google AppEngine.

Purge Post URL, Home, Blog and Terms page on update

---

src/WordPress/WordPressWrapper.php

When Wordpress MU Domain Mapping is enabled, use the primary domain for current blog, instead of default subdomain.
Example scenario:
| wp-admin | PRIMARY DOMAIN | blog_id |
| --- | --- | --- |
| example.com | example.com | 1 |
| it.example.com | www.example.it | 2 |
| fr.example.com | www.example.fr | 3 |
actually this plugin uses the example.com zone for all the domains.
With this PR the active zone is set to the Primary Domain setup in [Wordpress MU Domain Mapping](https://it.wordpress.org/plugins/wordpress-mu-domain-mapping/).

Map active zone to Primary Domain

---

.travis.yml
README.md

Some notes:
1. php/mock requires PHP >= 5.5. I'm not sure what to do in order to test all the supported by cloudflare-WordPress plugin PHP versions, so I skipped 5.3 and 5.4. IMO we should definitely test all supported versions to prevent accidental breakage.
2. I left `fast_finish` out and HHVM.
Finally. before merging this, you will need to add Travis CI to the repo and enable "Build only if .travis.yml is present" in the Travis project's settings.
Until then you can have a quick look https://travis-ci.org/XhmikosR/Cloudflare-WordPress/builds
Fixes #143.

Add .travis.yml for Travis CI testing.

---

README.md
composer.json
readme.txt
src/WordPress/Hooks.php
src/WordPress/WordPressClientAPI.php

Removes the php-curl dependency.
Fixes #113.
This is #134, formatted, rebased and squashed.

WP Client API uses WP_HTTP class instead of Guzzle.

---

composer.json

Only downside I see from this is when one has `php5` and not `php`, but I think it's symlinked so it should be OK.
Let me know your thoughts.

composer.json: Windows compatibility.

---

src/WordPress/Hooks.php

Actually the plugin only purges category and tag terms, but there are many situations where a post has public custom taxonomies that needs to be purged on post update.
This will purge the terms pages for all taxonomies (including tags and categories) registered with the post's post_type.

Purge all post related taxonomies terms

---

index.php

Note that I kept the bracket notation for properties to match the PHP code.
Only things I'd personally improve, is to explicitly set global variables to the global scope so that it's clear what is what. But that's for another time.

index.php: consistent formatting for inline JS.

---

scripts/deployment/trim_code_for_release.sh

* switch to the dist folder before doing anything; reduces duplication
* remove `-r` when removing compiled.js.map
* remove .gitignore
* remove all test folders from vendor subfolders
Saves ~100KB from the distribution archive.
Looking at v3.0.0 which weighted **4.0 MB**, v3.1.1 weighted **2.5 MB**, and the next release should be **~1.54 MB** if the rest of my PRs are merged. Not bad :)

Tweak trim_code_for_release.sh.

---

cloudflare.php

We needed to do this because everytime the plugin updates, users would lose the setting they've set

PI-993 move HTTP2 server push file to wp-config.php

---

cloudflare.loader.php

If the named constant `CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE` is not defined in` wp-config.php` PHP uses it's name as value and enables the feature by default. It also shows warnings. 
Better check if it's defined before.

Check if constant CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE is defined

---

src/WordPress/WordPressWrapper.php

This is one of the bugs we couldn't find out where `Please select a domain that is provisioned with CloudFlare` was showing.

PI-1058 fixed a bug where domain needed to be lowercased

---

cloudflare.loader.php

This PR will need the article to change:
https://support.cloudflare.com/hc/en-us/articles/115002708027-What-does-Automatic-Cache-Management-in-the-Cloudflare-Plugin-do-
`autoptimize_action_cachepurged` should be needed to move to cache everything part. 
FYI @IcyApril I'll let you know when a release happens.

PI-1072 move autoptimize to purge everything instead of per URL

---

src/WordPress/Hooks.php

I assume WordPress 4.8 introduced introduced a constant called `WP_AJAX_ACTION` with a different value from `Hooks::WP_AJAX_ACTION`.  
By using `self` instead of the global `const` we ensure we use our value.

PI-1198: Making consts in Hooks.php more specific to fix bug.

---

cloudflare.loader.php
src/WordPress/Hooks.php

To modify the list of URLs that eventually get purged by Cloudflare through the wordpress plugin a new filter was introduced. The is related to the earlier PR #194 and has the suggesting made by @thellimist

Adding  a new filter cloudflare_purge_by_url

---

composer.json
phpcs.xml
src/WordPress/Hooks.php
src/WordPress/WordPressAPI.php

Fixes errors related to attempts to treat string $wpDomain as countable type. This should also address errors relating to headers already being sent due to the Warnings output by PHP when encountering the mismatched type: 
```
$ vendor/bin/phpunit
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.
..........................................
Time: 104 ms, Memory: 6.00MB
OK (42 tests, 115 assertions)
```

PI-1272 Fix countable error in PHP 7.2+

---

src/WordPress/HTTP2ServerPush.php

These changes fix a compatibility issue with the Cloudflare plugin's HTTP/2 server push feature and the Autoptimize plugin's script and stylesheet concatenation and minification feature. 
```
$ composer format && composer test
> php vendor/squizlabs/php_codesniffer/scripts/phpcs -d date.timezone=UTC -n --standard=phpcs.xml
> php vendor/phpunit/phpunit/phpunit
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.
..........................................
Time: 106 ms, Memory: 6.00MB
OK (42 tests, 115 assertions)
```

Fix HTTP/2 server push breaking Autoptimize plugin

---

src/WordPress/PluginActions.php

WordPress works fine over IPv6, so update the default setting to reflect that.

Turn on IPv6 by default

---

cloudflare.loader.php

Fixes https://github.com/cloudflare/Cloudflare-WordPress/issues/204 issue, where HTTP/2 Push produce too big headers causing Cloudflare 502 Bad Gateway error while on WordPress Admin Panel pages. 
[`is_admin()`](https://codex.wordpress.org/Function_Reference/is_admin) returns true for admin pages and is clean solution.

Disable HTTP/2 Push on wp-admin pages, fixes #204

---

src/WordPress/Hooks.php

Don't set cf-edge-header if headers already sent. (Fixes #305, Fixes #302)

check if headers have been sent before setting cf-edge-cache

---

cloudflare.php
composer.json
composer.lock
config.json
readme.txt
vendor/composer/installed.json
vendor/sebastian/code-unit-reverse-lookup/ChangeLog.md
vendor/sebastian/code-unit-reverse-lookup/composer.json
vendor/sebastian/code-unit-reverse-lookup/tests/WizardTest.php

= 3.8.7 - 2020-12-07 =
* Purge taxonomy feed URLs
* Fix changing APO settings (cf, wordpress, plugin) when running on subdomain
* Fix setting hostname override

Release v3.8.7

---

cloudflare.loader.php
src/WordPress/Hooks.php

The existing implementation of the Cloudflare plugin triggers a cache purge whenever a new comment is added, no matter if the comment might be held for moderation. My PR proposes a change in order to make cache purging "aware" of comment status and only act (e.g. purge cache) upon significant/visible changes with regard to the post.

Change purge logic for comments

---

src/WordPress/PluginActions.php

During the CI revamp, we pulled out a manual step that would copy the
`composer.json` file into the same directory as the `PluginsActions`
class. This seems quite verbose so instead of restoring that
functionality, let's just reuse the root level files.
Closes #380

read root level composer + user configuration files

---

.github/workflows/php.yml
composer.json
composer.lock
src/Test/WordPress/PluginActionsTest.php
src/WordPress/PluginActions.php
src/WordPress/Proxy.php

This PR started off as adding PHP 8.0 to the build matrix in order to test what our upgrade position will be once we decided to roll to PHP 8.0 however upon running an initial test, the only failures were a couple of tests so I decided to unpin the dependencies at the same time. By doing this, we're no longer running out of date development dependencies with a weird versioning web of constraints; we're running the latest stable available.
The changes here are `development` only (dev-deps and tests) so there shouldn't be any end user changes expected.

Unpin dev dependencies, add PHP 8 support

---

cloudflare.loader.php
src/WordPress/Hooks.php

Currently if a post was published publicly and then gets set to private, no cache purge is done, even though that's exactly what you would expect to happen in that case. This is because the hook returns early unless the post is "publish" or "trash" status. I changed it so that if a post is private but it was not private previously (i.e. when the private status is being applied), it still executes the purge.
* Add ...$args to the hook to avoid doing additional queries. This could
likely be used elsewhere in the function instead of querying those
things.
* Make "private" also a "valid" post status, add extra check to still
skip purge unless it's a status change.

Purge posts that go from public to private.

---

cloudflare.loader.php
src/WordPress/Hooks.php

Second try to fix https://github.com/cloudflare/Cloudflare-WordPress/issues/337. In addition to previous https://github.com/cloudflare/Cloudflare-WordPress/pull/339/files I limit the number of pages to 3.
Also APO applies Edge Cache TTL of 30 mins for all `example.com/page/*` paginated urls.

Purge pagination

---

cloudflare.loader.php
src/WordPress/Hooks.php

This includes publish => publish transitions (editing a published post), manually publishing a post, unpublishing a post, or WordPress automatically publishing a scheduled post at the appropriate time.
I removed the `post_updated` hook because it would be redundant, and the current architecture of the plugin would result in multiple purge requests being sent for the same post update.
see #396 (different approach)
fixes #395

Purge a post from APO when its status transitions to or from "publish"

---

src/WordPress/Hooks.php

Hello everyone 👋
by trying to correct the problem mentioned here: #404 
I found 2 small improvements:
I noticed that if the user has a private taxonomy, we still send in the table of urls) delete urls to Cloudflare on not-public taxonomy.
In itself it is not annoying, but in the case of many urls, we limit calls to Cloudflare by being more efficient.
Likewise it can happen that by the specific construction of custom taxonomy we refuse the feed urls.
Line [192](https://github.com/cloudflare/Cloudflare-WordPress/blob/64fcc91f53d8599b5ca80b3f4430c9f61d8cdd01/src/WordPress/Hooks.php#L192) empty referral.
I added a small row that will clean up the empty rows in the table.
Thank you

Small fix on the list of urls to clear the cache

---

.github/workflows/php.yml
composer.json
composer.lock
src/WordPress/ClientActions.php
src/WordPress/DataStore.php
src/WordPress/WordPressClientAPI.php
src/WordPress/WordPressWrapper.php

In order to determine the zone identifier, the plugin makes a call to
the Cloudflare API and fetchs all the zones the authorization method has
access to. From there, it compares the API response with the site
domain. Unfortunately, in the process of getting to the comparison the
value isn't always utf8 compatible resulting in a missed lookup even
though the zone is actually found in the API result as a utf8 value.
To rectify this, I've updated the comparisons to always convert to ASCII
before performing the comparison which ensures that if either WordPress
or the Cloudflare API respond with something in UTF8 or ASCII, we will
always find it correctly. I opted for ASCII comparisons (and storage)
here for two main reasons. The first is that not all database storage
systems available to …

Support IDN domain comparison

---

src/WordPress/Hooks.php

`wp_get_attachment_image_src()` can return `false` for a given postId/size combo, in which case we should skip past it.
The lack of this test is causing this:
`Trying to access array offset on value of type bool`

Only add attachment URL to purge list if WordPress provides info about it

---

cloudflare.loader.php

* The `transition_post_status` hook is actually misnamed, since it also
runs when the status doesn't change but the post is edited. This plugin
relies on this behavior to purge published posts on changes. I copied
and slightly authored the documentation for this that was only present
in [the PR description](https://github.com/cloudflare/Cloudflare-WordPress/pull/397#issue-597536270).

Document unintuitive WP hook behavior

---

cloudflare.php
composer.json
composer.lock
config.json
readme.txt

* Document unintuitive `transition_post_status` WP hook behavior
* Only purge public taxonomies while clearing any empty values from the list
* Better handling of cases where `wp_get_attachment_image_src` is false and not a usable array
* Support activation of IDN domains
* Improve development experience by shipping a Docker Compose file with more tooling and documentation

Prepare 4.5.0

---

.github/workflows/php.yml
.github/workflows/release.yml

As a part of our deployment pipeline, we push the compiled plugin to
WordPress's SVN server. Unfortunately, the [SVN precommit hook does not
yet support PHP 8](https://meta.trac.wordpress.org/ticket/3791) (which Symfony's intl/idn polyfill includes).
Despite WordPress only offering PHP 8 support in a [beta](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/) [capacity](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/),
people are running PHP 8 in production and the 4.5.0 release which
caused some sites unusable.
While this isn't ideal as we are rewriting the vendored package
contents, this does workaround the issue by removing the PHP 8 feature
that is causing the lint failure while still leaving the file in a
usable state.

rewrite symfony/polyfill bootstrap80.php contents instead of deleting

---

.gitignore
Dockerfile.wordpress
composer.json
composer.lock
src/API/AbstractAPIClient.php
src/API/Client.php
src/API/DefaultHttpClient.php
src/Test/API/AbstractAPIClientTest.php
src/Test/API/DefaultHttpClientTest.php

Closes #445 
This PR is _probably_ incomplete. A couple notes:
- Moves away from Guzzle exception classes. Replaced with what I considered sensible alternatives, but this will alter the logs that result from failed requests
- Inexperienced with stubbing WordPress core functions, so you may desire more comprehensive testing
- Docker image wouldn't build w/o adding an argument to `apt-get update`
But that said, all tests pass and I'll be giving this a go on a staging client site.

Remove Guzzle in favor of WordPress core functions

---

src/Test/WordPress/UtilsTest.php
src/WordPress/Hooks.php
src/WordPress/Utils.php
src/WordPress/WordPressClientAPI.php

This PR focuses on improving the accuracy and number of URLs that we end up 
sending to the cache purge service. Included are three improvements:
**Don't attempt to purge URLs outside of the current zone**
Cache purge requests are tied to credentials and if those credentials don't 
match the current zone, the URL is thrown away. 
**Don't purge non-public facing posts** 
Many systems have a concept of "public facing" content; this is content that is 
designed for end users. Previously, we didn't take into account things like 
backend URLs, posts that were private and content that wouldn't ever be in the 
caches. With this change, we'll rely on the WordPress context to determine if
the content is publicly queryable and subsequently, purgable.
**Only purge cachable file extensions unless we …

More efficient cache purge 

---

src/WordPress/Hooks.php

Updates the filtering to allow using subdomains within WordPress. Other
parts of the code ignore subdomains entirely but this was incorrectly
doing a strict comparison.

relax cache purge domain check

---

src/WordPress/Hooks.php
src/WordPress/WordPressClientAPI.php

In a bid to further reduce the number of URLs we send to the cache purge
service, we can check if the zone has "always_use_https" enabled
(without a page rule override) and should it, remove any HTTP URLs as
they won't be getting hit in cache.

if `always_use_https` enabled, only purge HTTPS URLs

---

docs/release-new-version.md
scripts/bump-plugin-version.sh

Introduce a script that handles bumping all the places we define the
plugin version so we don't forget and cause misinformation in the user
agent being sent.

add scripts/bump-plugin-version.sh

---

src/WordPress/Hooks.php

Saving changes on a page was not triggering cache purge for that page. Condition for testing used check for publicly_queryable prop, which by default return false for pages. However WP has build-in function for checking if queried object can be publicly viewed and returns correct values for all types of posts.

Fix for APO not purging cache on page save

---

src/WordPress/Hooks.php

Updates the `pageRuleContains` functionality to account for
`always_use_https` lacking a "value".
Additionally removes the override check as it isn't possible to do; you
can only enable the `always_use_https` for a given URL.
Closes #465
Closes #467

handle `always_use_https` lacking a page rules "value"

---

src/WordPress/Hooks.php

I have a use case that would have required many extraneous requests to clear related urls from the cache.
Use case: Woocommerce coupon is updated. Products that are valid for this coupon and their related links need to be cleared from cache.
Problem: Cloudflare module allows me to clear related links based on a single post id.  In my case, there is significant overlap between the related posts.  Causes many extra requests to clear urls.
Solution: Allow for either a postId or postIds array to be process by Hooks purgeCacheByRelevantURLs.  Aggregate all related links and apply array_unique to only clear overlapping urls once.
Results:
For 24 products (posts) that need their related links cleared, pull request reduces the amount of API requests from 31 to 7 (442% decrease) and the amount of …

Allow clearing cache for array of post ids or single post id

---

src/WordPress/Hooks.php

current logic filters out NON feed urls:
while we want to filter out unnecessary feed urls and keep everything else:
This fixes the issue reported in https://github.com/cloudflare/Cloudflare-WordPress/issues/484

fix logic for skipping purging unnecessary feed urls

---

src/WordPress/Hooks.php

Use case: Woocommerce customers with role customer should also be served cached pages from cloudflare.  Added a hook to allow the cache state boolean to be manipulated.

Add filter to allow developers to determine cache usage

---

.distignore
.htaccess

After installation, this plugin creates a file called output.log which is publicly accessible if the web server is not explicitly configured to block direct access to this type of file.
Consequently I have added a file called .htaccess which, for users using Apache web server, allows direct public access only to images, fonts, js and css files specific to this plugin.
So it restricts direct public access to files like config.json, output.log, readme.txt, LICENSE.md, etc.
This is a similar configuration to that used by Akismet in their open source plugin. See details here: https://github.com/wp-plugins/akismet/blob/master/.htaccess
In addition I added the docker_tag file and the xdebug and .vscode folders to the list of files and folders that are ignored when creating a new package that is …

Restrict access

---

src/WordPress/Hooks.php

Closes #488 
This PR should fix the issue where the cache for a URL won't get purged if it's defined as an array, for example if there are headers .

Updates purgeCacheByRelevantURLs filter to allow arrays

---

src/WordPress/Hooks.php

I received this error on my site:
> Trying to access array offset on value of type null
Because `CF\WordPress\Hooks::zoneSettingAlwaysUseHTTPSEnabled()` got back a null from `$this->api->getZoneSetting($zoneTag, "always_use_https")` and then tried to access `["value"]` on that null.
This adds some sanity checks on the value. Note that this will default the return value to `false` if the zone setting comes back as null — I think that's a reasonable assumption.
Using older PHP syntax for this check to retain maximum compatibility (WordPress unfortunately still runs on PHP 5.6).

Ensure that getZoneSetting() returns a value key before attempting to access it

---

cloudflare.php
composer.json
composer.lock
config.json
readme.txt

This release deploys the following revert https://github.com/cloudflare/Cloudflare-WordPress/pull/516.

release 4.12.2

---

src/Integration/IntegrationAPIInterface.php
src/Test/WordPress/HooksTest.php
src/Test/WordPress/ProxyTest.php
src/WordPress/Proxy.php
src/WordPress/WordPressAPI.php
src/WordPress/WordPressWrapper.php

**🔖 Summary**
The implementation of this plugin is hidden behind a [`is_admin()` WordPress function](https://developer.wordpress.org/reference/functions/is_admin/).
However, as stated in the documentation:
> Does not check if the user is an administrator; use current_user_can()
> for checking roles and capabilities.
This commit is about ensuring that the `cloudflare_proxy` action on the
/admin-ajax endpoint is correctly limited to Administrator users only
before making any call via the Proxy to Cloudflare.
**✅ Testing plan**
Update the mocked tests which were rightfully failing due to non-Administrator
calls.

Prevent usage of `cloudflare_proxy` action on /admin-ajax endpoint for non-Administrator users

---

src/WordPress/DataStore.php
src/WordPress/Proxy.php

Removes the following deprecation warning son PHP 8.2
```PHP
Deprecated: Creation of dynamic property CF\WordPress\DataStore::$logger is deprecated in /var/www/public_html/public/content/mu-plugins/cloudflare/src/WordPress/DataStore.php on line 23
Deprecated: Creation of dynamic property CF\WordPress\Proxy::$pluginAPI is deprecated in /var/www/public_html/public/content/mu-plugins/cloudflare/src/WordPress/Proxy.php on line 31
```

Fix "creation of dynamic property is deprecated" notice

---

src/WordPress/ClientActions.php
src/WordPress/WordPressClientAPI.php

We recently noticed that a user got its zone incorrectly reported as inactive by the Wordpress plugin. After some investigations, it seems that two zones actually existed: an old purged one, and a new active zone. To guarantee that the plugin always retrieve the active one, if any, this commit changes the zone retrieval call to the Cloudflare API by adding a `status=active` query parameter to the request, [as documented here](https://developers.cloudflare.com/api/operations/zones-get).

CUSTESC-36595: Retrieve the Wordpress domain only from the active zone

---

cloudflare.php
composer.json
composer.lock
config.json
readme.txt

**🔖 Summary**
This release includes two minor fixes.
First one is making sure that the only the active zone is fetched when retrieving the customer zone, preventing accidental fetching of a purged zone with the same name, which happened to at least one customer.
Second change is about preventing some error banners from appearing on the user plugin page, which was due to failing calls to retrieve details about the Railgun settings of the user, which is now deprecated by Cloudflare, and whose endpoints have been decomissioned.
**🚧 Changes**
- [CUSTESC-36595: Retrieve the Wordpress domain only from the active zone](https://github.com/cloudflare/Cloudflare-WordPress/pull/532)
- [SPEED-777: Upgrade cloudflare-plugin-frontend to v3.8.0](https://github.com/cloudflare/Cloudflare-WordPress/pull/535 …

release 4.12.5

---

cloudflare.php
composer.json
composer.lock
config.json
readme.txt

**🔖 Summary**
This release includes https://github.com/cloudflare/Cloudflare-WordPress/pull/542 which corresponds to the output of the `yarn build:production` of version `3.10.0` of the `cloudflare-plugin-frontend` plugin to include the potential fix introduced by cloudflare/cloudflare-plugin-frontend#200.

release 4.12.7
